site_name: STClass
site_description: Documentation for STClass
site_author: Odin
site_url: https://anhvipx266.github.io/stclass/
repo_url: https://github.com/anhvipx266/STClass
repo_name: STClass
copyright: Copyright &copy; 2021 - 2025 Odin - An

nav:
  - Home: index.md

theme:

  name: material
  font:
    text: Ubuntu
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
  highlightjs: true
  hljs_languages:
    - lua
