site_name: STClass
site_description: Documentation for STClass
site_author: Odin
site_url: https://anhvipx266.github.io/stclass/
repo_url: https://github.com/anhvipx266/STClass
repo_name: STClass
copyright: Copyright &copy; 2021 - 2025 Odin - An

nav:
  - Home: index.md

